import Head from "next/head";

import axios from "axios";
import BlogContainer from "@/components/BlogContainer";

export async function getServerSideProps() {
  const { data } = await axios.get("http://localhost:3000/api/blogs");

  return {
    props: {
      blog: data[0],
    },
  };
}

export default function Home({ blog }) {
  return (
    <>
      <Head>
        <title>{blog.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* Blog */}
        <BlogContainer title={blog.title} descriptions={blog.descriptions} />
      </main>
    </>
  );
}
