import Head from "next/head";
import BlogCards from "@/components/BlogCard";
import styles from "@/styles/blog-card.module.css";
import axios from "axios";
import { useEffect, useState } from "react";

// export async function getServerSideProps() {
//   const { data } = await axios.get("http://localhost:3000/api/blogs");

//   return {
//     props: {
//       blogs: data,
//     },
//   };
// }

export default function Home() {
  const [blogs, setBlogs] = useState([]);
  useEffect(() => {
    const { data } = axios
      .get("http://localhost:3000/api/blogs")
      .then((res) => setBlogs(res.data));
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* Blogs */}

        <div id="blog-card-container" className={styles.blogCardContainer}>
          {blogs.map((blog, i) => (
            <BlogCards
              key={i}
              {...{ title: blog.title, description: blog.description }}
            />
          ))}
        </div>
      </main>
    </>
  );
}
