import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>CMS Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Home Page</h2>
        <ol>
          <li>Header Navs</li>
          <li>Login</li>
          <li>Register</li>
          <li>
            Blog List
            <ul>
              <li>Best Picks</li>
              <li>category</li>
            </ul>
          </li>
        </ol>
      </main>
    </>
  );
}
