import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
// import { basicTemplate } from "@/templates/basic";

const inter = Inter({ subsets: ["latin"] });

// const Elements = basicTemplate();

export default function Home() {
  const getElement = (item) => {
    if (item.type === "text") {
      return (
        <div>
          <h2>Hello</h2>
          <label>{item.label}</label>
          <input type={item.text} placeholder={item.placeholder} />
        </div>
      );
    }
  };

  const getElementsFromTemplate = (template) => {
    const elements = [];
    for (ele of template.elements) {
      if (ele.customType) elements.push(ele);
      elements.push(getElement(ele));
    }

    return elements;
  };

  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>Hello</>
   
        {/* {Elements.elements.map(getElementsFromTemplate)} */}
      </main>
    </>
  );
}
